CREATE TABLE ATTENDANCE (
ID BIGSERIAL PRIMARY KEY,
DATE TIMESTAMP NOT NULL,
USER_ID BIGINT NOT NULL REFERENCES USER(ID)
);

INSERT INTO USER (USER_NAME, PASSWORD_ENCODED) VALUES ('Simon', '123456');

